mixed-port: 7890
log-level: error
ipv6: true
allow-lan: false

external-controller: "127.0.0.1:9090"
external-ui: ui
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"

unified-delay: false
tcp-concurrent: true

profile:
  store-selected: true
  store-fake-ip: true

tun:
  enable: true
  stack: system
  mtu: 1500
  dns-hijack:
    - "udp://any:53"
    - "tcp://any:53"
  auto-route: true
  auto-detect-interface: true
  disable-icmp-forwarding: true

dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "+.market.xiaomi.com"
    - "lancache.steamcontent.com"
  default-nameserver:
    - "223.6.6.6"
  proxy-server-nameserver:
    - "https://dns.alidns.com/dns-query"
  nameserver:
    - "quic://dns.alidns.com"

hosts:
  "dns.alidns.com": ["223.5.5.5", "223.6.6.6"]
  "dns.google": ["8.8.8.8", "8.8.4.4"]

proxy-groups:
  - name: 🚀 手动选择
    type: select
    include-all: true
    include-all-proxies: true
    include-all-providers: true
    proxies:
      - ♻️ 自动选择
      - 📦 代理集合
      - ⛓️‍💥 代理节点
  - name: ♻️ 自动选择
    type: url-test
    include-all: true
    include-all-proxies: true
    include-all-providers: true
    proxies:
      - 📦 代理集合
      - ⛓️‍💥 代理节点
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 手动选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - 📦 代理集合
      - ⛓️‍💥 代理节点
  - name: AI
    type: select
    include-all: true
    include-all-proxies: true
    include-all-providers: true
    proxies:
      - 🚀 手动选择
      - ♻️ 自动选择
      - 📦 代理集合
      - ⛓️‍💥 代理节点
  - name: TG
    type: select
    include-all: true
    include-all-proxies: true
    include-all-providers: true
    proxies:
      - 🚀 手动选择
      - ♻️ 自动选择
      - 📦 代理集合
      - ⛓️‍💥 代理节点

rules:
  - DOMAIN,abyss.cyapi.cn,REJECT
  - DOMAIN,ad.cyapi.cn,REJECT
  - DOMAIN,gather.colorfulclouds.net,REJECT
  - RULE-SET,private,DIRECT
  - RULE-SET,private_ip,DIRECT,no-resolve
  - RULE-SET,ai,AI
  - RULE-SET,telegram,TG
  - RULE-SET,telegram_ip,TG,no-resolve
  - RULE-SET,github,🚀 手动选择
  - RULE-SET,twitter,🚀 手动选择
  - RULE-SET,youtube,🚀 手动选择
  - RULE-SET,google,🚀 手动选择
  - RULE-SET,gfw,🚀 手动选择
  - RULE-SET,cn,DIRECT
  - RULE-SET,cn_ip,DIRECT
  - MATCH,🐟 漏网之鱼

rule-providers:
  private:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    path: ./rule_providers/private.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"
  private_ip:
    type: http
    behavior: ipcidr
    format: mrs
    interval: 86400
    path: ./rule_providers/private_ip.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"
  ai:
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    path: ./rule_providers/ai.yaml
    url: "https://kelee.one/Tool/Clash/Rule/AI.yaml"
  telegram:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    path: ./rule_providers/telegram.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"
  telegram_ip:
    type: http
    behavior: ipcidr
    format: mrs
    interval: 86400
    path: ./rule_providers/telegram_ip.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"
  github:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    path: ./rule_providers/github.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"
  twitter:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    path: ./rule_providers/twitter.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.mrs"
  youtube:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    path: ./rule_providers/youtube.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"
  google:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    path: ./rule_providers/google.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"
  gfw:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    path: ./rule_providers/gfw.mrs
    url: "https://raw.githubusercontent.com/wwqgtxx/clash-rules/release/gfw.mrs"
  cn:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    path: ./rule_providers/cn.mrs
    url: "https://static-file-global.353355.xyz/rules/cn-additional-list.mrs"
  cn_ip:
    type: http
    behavior: ipcidr
    format: mrs
    interval: 86400
    path: ./rule_providers/cn_ip.mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"
